### ISSUE TITLE
--bytype option gives error

### ISSUE THREAD

**Issue by antulik** [oleander/git-fame-rb#12]
git fame works fine, but --bytype raises exception

```
$ git fame --bytype
Blame:         100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time:   0:01:07

Total number of files: 1,524
Total number of lines: 158,853
Total number of commits: 1,001
/Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:10:in `test': wrong number of arguments (0 for 2..3) (ArgumentError)
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:10:in `block (2 levels) in render'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:10:in `each'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:10:in `inject'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:10:in `block in render'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:9:in `each'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:9:in `inject'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/object_table.rb:9:in `render'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/helpers/auto_table.rb:22:in `render'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/formatter.rb:73:in `_format_output'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/formatter.rb:56:in `format_output'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/view.rb:204:in `render_output'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/console.rb:18:in `render_output'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/hirb-0.7.2/lib/hirb/console.rb:30:in `table'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:37:in `pretty_puts'
	from /Users/anton/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_fame-1.2.1/bin/git-fame:26:in `<top (required)>'
	from /Users/anton/.rbenv/versions/2.0.0-p353/bin/git-fame:23:in `load'
	from /Users/anton/.rbenv/versions/2.0.0-p353/bin/git-fame:23:in `<main>'
```

**Comment by oleander** [comment]
I think this should be fixed after #14 was merged. Otherwise feel free to open the issue again.
