### ISSUE TITLE
Crash: tty-spinner terminates with exception

### ISSUE THREAD

**Issue by tvincent2** [oleander/git-fame-rb#133]
Hi!

I just installed git-fame-rb using `sudo gem install git_fame` and tried to run it on a project.
I get this crash:

```
$ git fame
[|] git-fame is crunching the numbers, hold on ...#<Thread:0x00007f25b4723ab8 /var/lib/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:308 run> terminated with exception (report_on_exception is true):
/var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `block in compact_blank': undefined method `blank?' for "HEAD":String (NoMethodError)

    reject { |_k, v| v.blank? }
                      ^^^^^^^
	from /var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `reject'
	from /var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `compact_blank'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:140:in `filter'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:152:in `collector'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:168:in `result'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:127:in `block in run'
	from /var/lib/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:225:in `execute_job'
	from /var/lib/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:308:in `block in run'
[|] git-fame is crunching the numbers, hold on ...
/var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `block in compact_blank': undefined method `blank?' for "HEAD":String (NoMethodError)

    reject { |_k, v| v.blank? }
                      ^^^^^^^
	from /var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `reject'
	from /var/lib/gems/3.1.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/enumerable.rb:218:in `compact_blank'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:140:in `filter'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:152:in `collector'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:168:in `result'
	from /var/lib/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:127:in `block in run'
	from /var/lib/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:225:in `execute_job'
	from /var/lib/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:308:in `block in run'
```

It does not look project-related because I get the same result on several, very different projects.

Since `tty-spinner` is the one terminating with an exception, I assume the issue is not directly related to git-fame itself, but it probably has to do with some dependencies incompatibilities. Unfortunately, I know next to nothing about Ruby, so I'm not sure how to troubleshoot this. Please let me know if I can help in any way. git-fame looks really cool and I'd really love to use it.

**Comment by mably** [comment]
Same probleme here :(
