### ISSUE TITLE
undefined method `blank?' for "HEAD":String (NoMethodError)

### ISSUE THREAD

**Issue by colonelpanic8** [oleander/git-fame-rb#137]
```
 [|] git-fame is crunching the numbers, hold on ...
/nix/store/fqwi4kf2f3vyh65rg3y56n48glla5108-ruby3.1-activesupport-7.1.3.3/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.3/lib/active_support/core_ext/enumerable.rb:218:in `block in compact_blank': undefined method `blank?' for "HEAD":String (NoMethodError)

    reject { |_k, v| v.blank? }
                      ^^^^^^^
        from /nix/store/fqwi4kf2f3vyh65rg3y56n48glla5108-ruby3.1-activesupport-7.1.3.3/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.3/lib/active_support/core_ext/enumerable.rb:218:in `reject'
        from /nix/store/fqwi4kf2f3vyh65rg3y56n48glla5108-ruby3.1-activesupport-7.1.3.3/lib/ruby/gems/3.1.0/gems/activesupport-7.1.3.3/lib/active_support/core_ext/enumerable.rb:218:in `compact_blank'
        from /nix/store/0faxkyqfksd0k0d5m99h8rgbf42cicv5-ruby3.1-git_fame-3.1.1/lib/ruby/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:140:in `filter'
        from /nix/store/0faxkyqfksd0k0d5m99h8rgbf42cicv5-ruby3.1-git_fame-3.1.1/lib/ruby/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:152:in `collector'
        from /nix/store/0faxkyqfksd0k0d5m99h8rgbf42cicv5-ruby3.1-git_fame-3.1.1/lib/ruby/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:168:in `result'
        from /nix/store/0faxkyqfksd0k0d5m99h8rgbf42cicv5-ruby3.1-git_fame-3.1.1/lib/ruby/gems/3.1.0/gems/git_fame-3.1.1/lib/git_fame/command.rb:127:in `block in run'
        from /nix/store/jp5ci2yayim3spr59c5znp241ck6hzy1-ruby3.1-tty-spinner-0.9.3/lib/ruby/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:225:in `execute_job'
        from /nix/store/jp5ci2yayim3spr59c5znp241ck6hzy1-ruby3.1-tty-spinner-0.9.3/lib/ruby/gems/3.1.0/gems/tty-spinner-0.9.3/lib/tty/spinner.rb:308:in `block in run'

**Comment by colonelpanic8** [comment]
I believe the issue is that a:

```
require 'active_support/core_ext'
```

is required.

**Comment by colonelpanic8** [comment]
Ah, actually it seem that this may have been fixed in https://github.com/oleander/git-fame-rb/pull/136

**Comment by colonelpanic8** [comment]
We need a release that contains that fix though. This is breaking this package in nixos
