### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by trajber** [oleander/git-fame-rb#22]
/var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `split': invalid byte sequence in UTF-8 (ArgumentError)ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| ETA:   0:00:00
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `block in populate'
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:125:in `call'
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:125:in `populate'
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:44:in `files'
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/lib/git_fame/base.rb:31:in `pretty_puts'
	from /var/lib/gems/1.9.1/gems/git_fame-1.2.1/bin/git-fame:19:in `<top (required)>'
	from /usr/local/bin/git-fame:23:in `load'
	from /usr/local/bin/git-fame:23:in `<main>'

**Comment by trajber** [comment]
After an update this error was solved.
