### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by steffenbr** [oleander/git-fame-rb#50]
I got this error with the ```--bytype``` option.
```
/var/lib/gems/1.9.1/gems/git_fame-1.7.3/lib/git_fame/author.rb:54:in `inc': wrong number of arguments (0 for 2) (ArgumentError)
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `block (2 levels) in render'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `each'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `inject'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:10:in `block in render'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `each'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `inject'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/object_table.rb:9:in `render'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/helpers/auto_table.rb:22:in `render'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/formatter.rb:73:in `_format_output'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/formatter.rb:56:in `format_output'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/view.rb:205:in `render_output'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/console.rb:18:in `render_output'
        from /var/lib/gems/1.9.1/gems/hirb-0.7.3/lib/hirb/console.rb:30:in `table'
        from /var/lib/gems/1.9.1/gems/git_fame-1.7.3/lib/git_fame/base.rb:77:in `pretty_puts'
        from /var/lib/gems/1.9.1/gems/git_fame-1.7.3/bin/git-fame:35:in `<top (required)>'
        from /usr/local/bin/git-fame:23:in `load'
        from /usr/local/bin/git-fame:23:in `<main>'
```

Hope that helps.

**Comment by oleander** [comment]
Thanks for your bug report. The topic is being discussed in #51.

**Comment by M2ohamad** [comment]
Still running into ArgumentError when using --by-type.
