### ISSUE TITLE
Error: could not run...

### ISSUE THREAD

**Issue by mathieucarbou** [oleander/git-fame-rb#52]
```
13:37 $ git fame --verbose --after=2015-08-01

git log --encoding=UTF-8 --pretty=format:'%cd' --date=local master | head -1
git log --encoding=UTF-8 --pretty=format:'%cd' --date=local master | tail -1
git rev-list --before='2015-07-31 23:59:59' --date=local 'master' | head -1
git diff --name-status --encoding=UTF-8 --date=local a5b6899fb93809eefd3f377ef8e1f1315e5e0834..master | grep -v '^D' | cut -f2-
git show master:'warning: inexact rename detection was skipped due to too many files.' | LC_ALL=C file --mime-type -
Error: Could not run 'git blame --encoding=UTF-8 -p -M --date=local a5b6899fb93809eefd3f377ef8e1f1315e5e0834..master  -- 'warning: inexact rename detection was skipped due to too many files.'' => fatal: no such path warning: inexact rename detection was skipped due to too many files. in master
```

```
13:37 $ git --version

git version 2.8.1
```

**Comment by oleander** [comment]
Thanks! I think I've manage to fix the problem, could you try again?

``` bash
gem cleanup git_fame
gem install git_fame --version 2.1.0
```

**Comment by mathieucarbou** [comment]
worked, but then I got another error:

```
14:10 $ git fame --after=2015-08-01
/Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:329:in `value': execution expired (Timeout::Error)                                                                                                                                            |
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:329:in `block (2 levels) in run'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open3.rb:93:in `popen3'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:328:in `block in run'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:327:in `run'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/memoist-0.14.0/lib/memoist.rb:209:in `run'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:314:in `execute'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:188:in `block in populate'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:179:in `each'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:179:in `populate'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/memoist-0.14.0/lib/memoist.rb:165:in `populate'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/lib/git_fame/base.rb:92:in `initialize'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/bin/git-fame:31:in `new'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/gems/git_fame-2.1.0/bin/git-fame:31:in `<top (required)>'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/bin/git-fame:23:in `load'
	from /Users/matc/.rvm/rubies/ruby-2.2.1/bin/git-fame:23:in `<main>'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matc/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by oleander** [comment]
Could you try version 2.2?

**Comment by oleander** [comment]
Just released 2.3. Could you try it?

``` bash
gem cleanup git_fame
gem install git_fame --version 2.3.0
git fame --after=2015-08-01
```

**Comment by mathieucarbou** [comment]
It worked :-) Thanks a lot!

**Comment by oleander** [comment]
Awesome! Thanks for your bug report!

**Comment by schultz9999** [comment]
I have a submodule and getting an error for its directory. Any hints? Thanks!
`
▶ git fame
Error: Could not run 'git --git-dir='/x/y/z/.git' --work-tree='/x/y/z' blame --encoding=UTF-8 -p -M --date=local master  -- 'my-submodule'' => fatal: no such path my-submodule in master.
Try --help for help.
`
