### ISSUE TITLE
undefined method `strip' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by phillip-kruger** [oleander/git-fame-rb#61]
Hi.
On Arch Linux, I am getting this error:

```
/home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:368:in `author_by_email': undefined method `strip' for nil:NilClass (NoMethodError)
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:212:in `block (2 levels) in populate'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:210:in `map'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:210:in `block in populate'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:319:in `execute'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:209:in `populate'
        from /home/phillip/.gem/ruby/2.3.0/gems/memoist-0.14.0/lib/memoist.rb:165:in `populate'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/lib/git_fame/base.rb:93:in `initialize'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/bin/git-fame:36:in `new'
        from /home/phillip/.gem/ruby/2.3.0/gems/git_fame-2.3.1/bin/git-fame:36:in `<top (required)>'
        from /home/phillip/.gem/ruby/2.3.0/bin/git-fame:23:in `load'
        from /home/phillip/.gem/ruby/2.3.0/bin/git-fame:23:in `<main>'
```

Any idea how to solve this ?

**Comment by tsikerdekis** [comment]
I just got this error as well. I can confirms this.
