### ISSUE TITLE
git fame execution instruction error 

### ISSUE THREAD

**Issue by jiaguolin** [oleander/git-fame-rb#91]
`git fame .`

then:

```
Traceback (most recent call last):
	2: from /usr/local/bin/git-fame:23:in `<main>'
	1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem git_fame (>= 0.a) with executable git-fame (Gem::GemNotFoundException)
```

my ruby version :2.5

**Comment by wangwanjie** [comment]
same problem here.
